### ISSUE TITLE
0.4.0 not published to maven repository

### ISSUE THREAD

**Issue by krivachy** [grpc-ecosystem/java-grpc-prometheus#24]
Hi @dinowernli, the [v0.4.0 release](https://github.com/grpc-ecosystem/java-grpc-prometheus/releases/tag/v0.4.0) doesn't seem to be published to the [maven repository](https://mvnrepository.com/artifact/me.dinowernli/java-grpc-prometheus).

Is this something you can do? Or is there another repository where 0.4.0 is published?

**Comment by krivachy** [comment]
I see that it's been published here: https://github.com/dinowernli/maven-repos/tree/master/me/dinowernli/java-grpc-prometheus/0.4.0

Is it possible to publish this to maven as well?

**Comment by rubda** [comment]
> Is it possible to publish this to maven as well?

I second this, is there any possibility to do this @dinowernli?

**Comment by nikunjy** [comment]
Ping. Can we release 0.4 and other changes there after  @dinowernli

**Comment by AngerM** [comment]
I didn't like having to use that other github based maven (and neither did my security team), so I forked it, ripped out bazel for gradle, setup github ci, and changed the default latency buckets to ones I've found more useful in my experience. I had to rip out some of the unit tests for now just to simplify the transition from bazel->gradle but plan on adding them back shortly.

Fork: https://github.com/AngerM/java-grpc-prometheus
Maven Central: https://search.maven.org/artifact/dev.angerm.grpc.prometheus/java-grpc-prometheus
v0.1.1 has been published and should show up in maven central shortly as soon as sonatype finishes their sync

**Comment by dinowernli** [comment]
Apologies for the delay. I've cleaned up the repo and published version 0.5.0, see https://oss.sonatype.org/#nexus-search;quick~java-grpc-prometheus . Going to close this, assuming that we don't *also* need to publish 0.4.0 now that we have 0.5.0.

Please reopen if there are any issues left.
