### ISSUE TITLE
How to export metrics from gRPC server

### ISSUE THREAD

**Issue by rsmilyanov** [grpc-ecosystem/java-grpc-prometheus#8]
Hello guys,

Do you have some documentation how to export the collected metrics from ```MonitoringServerInterceptor``` to Prometheus?

I checked the code and it seems that I have export the metrics by myself. Am I right?

Thanks,
Rado

**Comment by dinowernli** [comment]
Hi Rado

Actually, the way Prometheus is usually set up looks as follows:
1) The binary in need of monitoring exports the relevant metrics
2) The binary in need of monitoring exposes an HTTP endpoint which surfaces
all metrics (can be done using a jetty servlet container and a simple
servlet)
3) A separate prometheus binary periodically scrapes the original binary.

This library helps you do (1). Solutions for (2) and (3) exist and are
largely shipped with Prometheus itself. Does this help?

Cheers
Dino

**Comment by rsmilyanov** [comment]
Hi @dinowernli,

yeah, I got to the same conclusions as well after some research.
Actually I decided to proceed with (2) approach.

Thanks for the for the information!

Best Regards,
Rado
